version = 0.1
[default.deploy.parameters]
stack_name = "serverless-stack"
resolve_s3 = true
s3_prefix = "IFAAC/serverless-stack"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
